import { Networks } from './network.types';
import { WalletProviders } from './wallet.types';

export type EnvConfig = {
  ENVIRONMENT:
    | 'dev'
    | 'pre-prod'
    | 'public-demo'
    | 'prod'
    | 'mantle-testnet'
    | 'mantle-mainnet'
    | 'mantle-mainnet-shadow';
  APP_NAME: string;
  PROPOSAL_ID: string;
  NETWORK: Networks;
  GANACHE_HTTP: string;
  GANACHE_WSS: string;
  HARDHAT_HTTP: string;
  HARDHAT_WSS: string;
  RINKEBY_HTTP: string;
  RINKEBY_WSS: string;
  SEPOLIA_HTTP: string;
  SEPOLIA_WSS: string;
  FORKED_MAINNET_HTTP: string;
  MAINNET_HTTP: string;
  MAINNET_WSS: string;
  FORKED_MAINNET_WSS: string;
  MANTLE_TESTNET_HTTP: string;
  MANTLE_TESTNET_WSS: string;
  MANTLE_MAINNET_HTTP: string;
  MANTLE_MAINNET_WSS: string;
  PHRASE_PROJECT_ID: string;
  API_URL: string;
  CONTRACTS: string;
  OFFCHAINER_URL: string;
  RISK_URL: string;
  APPSIGNAL_KEY: string;
  SWING_PROJECT_ID: string;
  UD_CLIENT_ID: string;
  UD_SCOPE: string;
  UD_REDIRECT_URL: string;
  NETWORK_SWITCHER_ETHEREUM_URL: string;
  NETWORK_SWITCHER_TAIKO_URL: string;
  NETWORK_SWITCHER_MANTLE_URL: string;
  WALLET_CONNECT_CHAIN_ID: number;
  MANTLE_BRIDGE_URL: string;
  METH_APY_SOURCE_URL: string;
  USDY_APY_SOURCE_URL: string;
  FEATURE: {
    GAS_ESTIMATION: boolean;
    DASHBOARD: boolean;
    ASSETS_BRIDGE?: boolean;
    GOVERNANCE: boolean;
    REFERRALS: boolean;
    HIDE_WALLETS: WalletProviders[];
    HIDE_ASSETS: string[];
    LEND: string[];
    WIDTHDRAW_DETAILS: string[];
    REPAY_DETAILS: string[];
    BORROW: string[];
    STAKE: boolean;
    WITHDRAW: boolean;
    AUTO_STAKING: boolean;
    PORTFOLIO: boolean;
    MARKET_AS_COLLATERAL: boolean;
    MNT_REWARDS: boolean;
    MNT_VESTING: boolean;
    TOTAL_RETURNS_CHART: boolean;
    TOTAL_NETAPY_CHART: boolean;
    TABLE_NFT_BOOST: boolean;
    GITHUB_LINK: boolean;
    HEALTH_FACTOR_GAUGE: boolean;
    GOVERNANCE_PARTICIPATION: boolean;
    COLLATERAL_TOGGLE: boolean;
    METAMASK_AMOUNT: boolean;
    METAMASK_ALLOWANCE: boolean;
    SWING: boolean;
    MANTLE_BRIDGE_BUTTON: boolean;
    NFT_TRANSFER_BUTTON?: boolean;
  };
};
